In [8]:
import pandas as pd
%matplotlib inline
from sklearn import datasets
from sklearn import tree
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [3]:
iris = datasets.load_iris() 

In [4]:
x = iris.data 
y = iris.target 
forest = RandomForestClassifier(n_estimators=5, random_state=2)
forest = forest.fit(x, y)

In [11]:
from sklearn.cross_validation import train_test_split
from sklearn import metrics

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25,train_size=0.75)

In [7]:
forest = forest.fit(x_train,y_train)

In [9]:
def measure_performance(X,y,clf, show_accuracy=True, show_classification_report=True, show_confussion_matrix=True):
    y_pred=clf.predict(X)
    if show_accuracy:
        print("Accuracy:{0:.3f}".format(metrics.accuracy_score(y, y_pred)),"\n")
    if show_classification_report:
        print("Classification report")
        print(metrics.classification_report(y,y_pred),"\n")
    if show_confussion_matrix:
        print("Confusion matrix")
        print(metrics.confusion_matrix(y,y_pred),"\n")

In [12]:
measure_performance(x_test,y_test,forest)

Accuracy:0.974 

Classification report
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        15
          1       0.91      1.00      0.95        10
          2       1.00      0.92      0.96        13

avg / total       0.98      0.97      0.97        38
 

Confusion matrix
[[15  0  0]
 [ 0 10  0]
 [ 0  1 12]] 

