Assignment 2

Using the readings, try and create a RandomForestClassifier for the iris dataset
Using a 25/75 training/test split, compare the results with the original decision tree model and describe the result to the best of your ability in your PR

In [2]:
import numpy as np
from sklearn import tree
from sklearn import metrics
from sklearn import datasets
from sklearn.ensemble import RandomForestClassifier
from sklearn.cross_validation import train_test_split

In [3]:
iris = datasets.load_iris()
x = iris.data[:,2:]
y = iris.target

In [4]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25,train_size=0.75)
forest = RandomForestClassifier(n_estimators=5, random_state=42)
forest.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=5, n_jobs=1,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [5]:
print("Training set accuracy: %f" % forest.score(x_train, y_train))
print("Testing set accuracy: %f" % forest.score(x_test, y_test))

Training set accuracy: 1.000000
Testing set accuracy: 0.947368


In [6]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25, train_size=0.25)
dt = tree.DecisionTreeClassifier()
dt = dt.fit(x_train, y_train)

def measure_performance(x,y,dt, show_accuracy=True, show_classification_report=True, show_confussion_matrix=True):
    y_pred=dt.predict(x)
    if show_accuracy:
        print("Accuracy:{0:.3f}".format(metrics.accuracy_score(y, y_pred)),"\n")
    if show_classification_report:
        print("Classification report")
        print(metrics.classification_report(y,y_pred),"\n")
    if show_confussion_matrix:
        print("Confusion matrix")
        print(metrics.confusion_matrix(y,y_pred),"\n")

In [7]:
print("Training set:") 
measure_performance(x_train, y_train,dt)

Training set:
Accuracy:1.000 

Classification report
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        12
          1       1.00      1.00      1.00        12
          2       1.00      1.00      1.00        13

avg / total       1.00      1.00      1.00        37
 

Confusion matrix
[[12  0  0]
 [ 0 12  0]
 [ 0  0 13]] 



In [8]:
print("Testing set:")
measure_performance(x_test,y_test,dt)

Testing set:
Accuracy:0.974 

Classification report
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        13
          1       0.93      1.00      0.96        13
          2       1.00      0.92      0.96        12

avg / total       0.98      0.97      0.97        38
 

Confusion matrix
[[13  0  0]
 [ 0 13  0]
 [ 0  1 11]] 

