Using the readings, try and create a RandomForestClassifier for the iris dataset
Using a 25/75 training/test split, compare the results with the original decision tree model and describe the result to the best of your ability in your PR

In [45]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_moons
from sklearn import cross_validation
import pandas as pd
%matplotlib inline
from sklearn import datasets
from sklearn import metrics
import matplotlib.pyplot as plt
import numpy as np
from sklearn import tree

In [4]:
iris = datasets.load_iris()

In [22]:
iris.data

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [27]:
x = iris.data[:,2:] # the attributes
y = iris.target # the target variable

In [29]:
x_train, x_test, y_train, y_test = cross_validation.train_test_split(x, y, stratify=y,random_state=42)
forest = RandomForestClassifier(n_estimators=5, random_state=2)
forest.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=5, n_jobs=1,
            oob_score=False, random_state=2, verbose=0, warm_start=False)

In [31]:
x_test

array([[ 1.3,  0.2],
       [ 4.7,  1.6],
       [ 1.3,  0.2],
       [ 4. ,  1.3],
       [ 1.4,  0.2],
       [ 4.5,  1.6],
       [ 5.6,  1.4],
       [ 5.8,  2.2],
       [ 5.1,  2.3],
       [ 5.6,  2.2],
       [ 4.5,  1.7],
       [ 4.5,  1.5],
       [ 4.4,  1.4],
       [ 4.5,  1.5],
       [ 1.7,  0.3],
       [ 1.5,  0.2],
       [ 1.7,  0.2],
       [ 4.7,  1.4],
       [ 1.2,  0.2],
       [ 5.6,  2.4],
       [ 5.2,  2. ],
       [ 5. ,  1.7],
       [ 3.3,  1. ],
       [ 5.8,  1.8],
       [ 6.3,  1.8],
       [ 5.5,  1.8],
       [ 3.3,  1. ],
       [ 1.3,  0.3],
       [ 4.9,  1.8],
       [ 1.5,  0.2],
       [ 3.9,  1.1],
       [ 5.4,  2.3],
       [ 4.8,  1.8],
       [ 1. ,  0.2],
       [ 1.4,  0.2],
       [ 1.2,  0.2],
       [ 1.7,  0.5],
       [ 4.6,  1.3],
       [ 4.5,  1.5]])

In [8]:
RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
max_depth=None, max_features='auto', max_leaf_nodes=None,
min_samples_leaf=1, min_samples_split=2,
min_weight_fraction_leaf=0.0, n_estimators=5, n_jobs=1,
oob_score=False, random_state=2, verbose=0, warm_start=False)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=5, n_jobs=1,
            oob_score=False, random_state=2, verbose=0, warm_start=False)

In [35]:
x_train, x_test, y_train, y_test = cross_validation.train_test_split(x, y, random_state=0, test_size=0.25, train_size=0.75)
forest = RandomForestClassifier(n_estimators=100, random_state=0)
forest.fit(x_train, y_train)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [36]:
print("accuracy on training set: %f" % forest.score(x_train, y_train))
print("accuracy on test set: %f" % forest.score(x_test, y_test))

accuracy on training set: 0.991071
accuracy on test set: 0.947368


Decision Tree Validation

In [39]:
dt = tree.DecisionTreeClassifier()

In [41]:
x_train, x_test, y_train, y_test = cross_validation.train_test_split(x,y,test_size=0.25,train_size=0.75)

In [42]:
dt = dt.fit(x_train,y_train)

In [43]:
def measure_performance(X,y,clf, show_accuracy=True, show_classification_report=True, show_confussion_matrix=True):
    y_pred=clf.predict(X)
    if show_accuracy:
        print("Accuracy:{0:.3f}".format(metrics.accuracy_score(y, y_pred)),"\n")
    if show_classification_report:
        print("Classification report")
        print(metrics.classification_report(y,y_pred),"\n")
    if show_confussion_matrix:
        print("Confusion matrix")
        print(metrics.confusion_matrix(y,y_pred),"\n")

In [46]:
measure_performance(x_test,y_test,dt)

Accuracy:0.947 

Classification report
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        13
          1       0.92      0.92      0.92        13
          2       0.92      0.92      0.92        12

avg / total       0.95      0.95      0.95        38
 

Confusion matrix
[[13  0  0]
 [ 0 12  1]
 [ 0  1 11]] 



In [47]:
measure_performance(x_train,y_train,dt)

Accuracy:1.000 

Classification report
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        37
          1       1.00      1.00      1.00        37
          2       1.00      1.00      1.00        38

avg / total       1.00      1.00      1.00       112
 

Confusion matrix
[[37  0  0]
 [ 0 37  0]
 [ 0  0 38]] 

